Separate the CI containers

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,125 +3,188 @@ name: CI
 on: [push, pull_request]
 
 jobs:
-  test-ubuntu:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -l -eo pipefail {0}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-      - name: Install build dependencies
-        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov
-      - name: Setup Python for testing
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.9'
-          architecture: 'x64'
-      - name: Install Python dependencies
-        run:
-          python -m pip install -r tests/flow/requirements.txt
-      - name: Checkout Redis
-        uses: actions/checkout@v2
-        with:
-          repository: 'redis/redis'
-          ref: 'unstable'
-          path: 'redis'
-      - name: Build Redis
-        run: cd redis && make -j 4
-      - name: Build
-        run: make -j 4
-      - name: Run tests
-        run: make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+  # test-ubuntu:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install build dependencies
+  #       run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov
+  #     - name: Setup Python for testing
+  #       uses: actions/setup-python@v1
+  #       with:
+  #         python-version: '3.9'
+  #         architecture: 'x64'
+  #     - name: Install Python dependencies
+  #       run:
+  #         python -m pip install -r tests/flow/requirements.txt
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v2
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: 'unstable'
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: cd redis && make -j 4
+  #     - name: Build
+  #       run: make -j 4
+  #     - name: Run tests
+  #       run: make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
 
-  test-valgrind:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -l -eo pipefail {0}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-      - name: Install build dependencies
-        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov valgrind
-      - name: Setup Python for testing
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.9'
-          architecture: 'x64'
-      - name: Install Python dependencies
-        run:
-          python -m pip install -r tests/flow/requirements.txt
-      - name: Checkout Redis
-        uses: actions/checkout@v2
-        with:
-          repository: 'redis/redis'
-          ref: 'unstable'
-          path: 'redis'
-      - name: Build Redis
-        run: cd redis && make valgrind -j 4
-      - name: Build
-        run: make -j 4
-      - name: Run tests
-        run: make test VG=1 REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+  # test-valgrind:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install build dependencies
+  #       run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov valgrind
+  #     - name: Setup Python for testing
+  #       uses: actions/setup-python@v1
+  #       with:
+  #         python-version: '3.9'
+  #         architecture: 'x64'
+  #     - name: Install Python dependencies
+  #       run:
+  #         python -m pip install -r tests/flow/requirements.txt
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v2
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: 'unstable'
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: cd redis && make valgrind -j 4
+  #     - name: Build
+  #       run: make -j 4
+  #     - name: Run tests
+  #       run: make test VG=1 REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
 
-  test-address-sanitizer:
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash -l -eo pipefail {0}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-      - name: Install build dependencies
-        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov valgrind
-      - name: Setup Python for testing
-        uses: actions/setup-python@v1
-        with:
-          python-version: '3.9'
-          architecture: 'x64'
-      - name: Install Python dependencies
-        run:
-          python -m pip install -r tests/flow/requirements.txt
-      - name: Checkout Redis
-        uses: actions/checkout@v2
-        with:
-          repository: 'redis/redis'
-          ref: 'unstable'
-          path: 'redis'
-      - name: Build Redis
-        run: cd redis && make SANITIZER=address -j 4
-      - name: Build
-        run: make -j 4
-      - name: Run tests
-        run: make test SAN=addr REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+  # test-address-sanitizer:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install build dependencies
+  #       run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov valgrind
+  #     - name: Setup Python for testing
+  #       uses: actions/setup-python@v1
+  #       with:
+  #         python-version: '3.9'
+  #         architecture: 'x64'
+  #     - name: Install Python dependencies
+  #       run:
+  #         python -m pip install -r tests/flow/requirements.txt
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v2
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: 'unstable'
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: cd redis && make SANITIZER=address -j 4
+  #     - name: Build
+  #       run: make -j 4
+  #     - name: Run tests
+  #       run: make test SAN=addr REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
 
-  centos:
+  # centos:
+  #   runs-on: ubuntu-latest
+  #   container: ${{ matrix.builder-container }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # TODO: figure out the Redis version we need to test on.
+  #       redis-version: ['unstable']
+  #       builder-container: ['centos:7']
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - name: Install build dependencies
+  #       run: |
+  #         yum -y install epel-release
+  #         yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
+  #         yum -y install gcc make cmake3 git python-pip openssl-devel bzip2-devel libffi-devel zlib-devel wget centos-release-scl scl-utils
+  #         yum groupinstall "Development Tools" -y
+  #         yum install -y devtoolset-10
+  #         . scl_source enable devtoolset-10 || true
+  #         make --version
+  #         gcc --version
+  #         git --version
+  #         wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
+  #         tar -xvf Python-3.9.6.tgz
+  #         cd Python-3.9.6
+  #         ./configure
+  #         make -j `nproc`
+  #         make altinstall
+  #         cd ..
+  #         rm /usr/bin/python3 && ln -s `which python3.9` /usr/bin/python3
+  #         ln -s `which cmake3` /usr/bin/cmake
+  #         python3 --version
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install Python dependencies
+  #       run: |
+  #         scl enable devtoolset-10 bash
+  #         python3 -m pip install -r tests/flow/requirements.txt
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: ${{ matrix.redis-version }}
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: |
+  #         cd redis && make -j `nproc`
+  #     - name: Build RedisBloom
+  #       run: |
+  #         . scl_source enable devtoolset-10 || true
+  #         make -j `nproc`
+  #     - name: Run tests
+  #       run: |
+  #         . scl_source enable devtoolset-10 || true
+  #         make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+
+  amazon-linux:
     runs-on: ubuntu-latest
     container: ${{ matrix.builder-container }}
     strategy:
       fail-fast: false
-      # TODO: figure out the version we need to test on.
       matrix:
+        # TODO: figure out the Redis version we need to test on.
         redis-version: ['unstable']
-        builder-container: ['centos:7', 'rockylinux:8', 'rockylinux:9', 'amazonlinux:2']
+        builder-container: ['amazonlinux:2']
     defaults:
       run:
         shell: bash -l -eo pipefail {0}
     steps:
       - name: Install build dependencies
         run: |
-          yum -y install epel-release
-          yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
-          yum -y install gcc make cmake3 git python-pip openssl-devel bzip2-devel libffi-devel zlib-devel wget centos-release-scl scl-utils
+          amazon-linux-extras install epel -y
+          yum -y install epel-release yum-utils
+          yum-config-manager --add-repo http://mirror.centos.org/centos/7/sclo/x86_64/rh/
+          yum search make
+          yum -y install gcc make cmake3 git python-pip openssl-devel bzip2-devel libffi-devel zlib-devel wget centos-release-scl scl-utils which
+          yum -y install devtoolset-11-gcc devtoolset-11-make --nogpgcheck
+          scl --list
           yum groupinstall "Development Tools" -y
-          yum install -y devtoolset-10
-          . scl_source enable devtoolset-10 || true
-          make --version
           gcc --version
+          . scl_source enable devtoolset-11 || true
+          make --version
           git --version
           wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
           tar -xvf Python-3.9.6.tgz
@@ -139,7 +202,7 @@ jobs:
           submodules: true
       - name: Install Python dependencies
         run: |
-          scl enable devtoolset-10 bash
+          scl enable devtoolset-11 bash
           python3 -m pip install -r tests/flow/requirements.txt
       - name: Checkout Redis
         uses: actions/checkout@v3
@@ -152,49 +215,110 @@ jobs:
           cd redis && make -j `nproc`
       - name: Build RedisBloom
         run: |
-          . scl_source enable devtoolset-10 || true
+          . scl_source enable devtoolset-11 || true
           make -j `nproc`
       - name: Run tests
         run: |
-          . scl_source enable devtoolset-10 || true
+          . scl_source enable devtoolset-11 || true
           make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
 
-  macos-x86_64:
-    runs-on: macos-13
-    strategy:
-      fail-fast: false
-      # TODO: figure out the version we need to test on.
-      matrix:
-        redis-version: ['unstable']
-    defaults:
-      run:
-        shell: bash -l -eo pipefail {0}
-    steps:
-      - name: Install prerequisites
-        run: |
-          brew install make
-      - name: Checkout sources
-        uses: actions/checkout@v3
-        with:
-          submodules: true
-      - name: Install Python dependencies
-        run: |
-          python3 -m pip install -r tests/flow/requirements.txt
-          python3 -m pip install setuptools
-      - name: Checkout Redis
-        uses: actions/checkout@v3
-        with:
-          repository: 'redis/redis'
-          ref: ${{ matrix.redis-version }}
-          path: 'redis'
-      - name: Build Redis
-        run: |
-          cd redis && make -j `sysctl -n hw.logicalcpu`
-      - name: Build RedisBloom
-        run: |
-          gmake -j `sysctl -n hw.logicalcpu`
-      - name: Run tests
-        run: |
-          gmake test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+
+  # rocky-linux:
+  #   runs-on: ubuntu-latest
+  #   container: ${{ matrix.builder-container }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # TODO: figure out the Redis version we need to test on.
+  #       redis-version: ['unstable']
+  #       builder-container: ['rockylinux:8', 'rockylinux:9']
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - name: Install build dependencies
+  #       run: |
+  #         yum -y install epel-release
+  #         yum -y install http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
+  #         yum -y install gcc make cmake3 git openssl-devel bzip2-devel libffi-devel zlib-devel wget scl-utils gcc-toolset-13
+  #         yum groupinstall "Development Tools" -y
+  #         . scl_source enable gcc-toolset-13 || true
+  #         make --version
+  #         gcc --version
+  #         git --version
+  #         wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
+  #         tar -xvf Python-3.9.6.tgz
+  #         cd Python-3.9.6
+  #         ./configure
+  #         make -j `nproc`
+  #         make altinstall
+  #         cd ..
+  #         rm /usr/bin/python3 && ln -s `which python3.9` /usr/bin/python3
+  #         # ln -s `which cmake3` /usr/bin/cmake
+  #         cmake --version
+  #         python3 --version
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install Python dependencies
+  #       run: |
+  #         . scl_source enable gcc-toolset-13 || true
+  #         python3 -m pip install -r tests/flow/requirements.txt
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: ${{ matrix.redis-version }}
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: |
+  #         cd redis && make -j `nproc`
+  #     - name: Build RedisBloom
+  #       run: |
+  #         . scl_source enable gcc-toolset-13 || true
+  #         make -j `nproc`
+  #     - name: Run tests
+  #       run: |
+  #         . scl_source enable gcc-toolset-13 || true
+  #         make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
+
+  # macos-x86_64:
+  #   runs-on: macos-13
+  #   strategy:
+  #     fail-fast: false
+  #     # TODO: figure out the version we need to test on.
+  #     matrix:
+  #       redis-version: ['unstable']
+  #   defaults:
+  #     run:
+  #       shell: bash -l -eo pipefail {0}
+  #   steps:
+  #     - name: Install prerequisites
+  #       run: |
+  #         brew install make
+  #     - name: Checkout sources
+  #       uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     - name: Install Python dependencies
+  #       run: |
+  #         python3 -m pip install -r tests/flow/requirements.txt
+  #         python3 -m pip install setuptools
+  #     - name: Checkout Redis
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: 'redis/redis'
+  #         ref: ${{ matrix.redis-version }}
+  #         path: 'redis'
+  #     - name: Build Redis
+  #       run: |
+  #         cd redis && make -j `sysctl -n hw.logicalcpu`
+  #     - name: Build RedisBloom
+  #       run: |
+  #         gmake -j `sysctl -n hw.logicalcpu`
+  #     - name: Run tests
+  #       run: |
+  #         gmake test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
 
 
